"""Add scan scores and report pdf to scan model

Revision ID: facc27c4fb29
Revises: e4c78cae4286
Create Date: 2025-04-12 00:35:57.002639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'facc27c4fb29'
down_revision = 'e4c78cae4286'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stepping_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('squat_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('posture_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('overall_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('report_pdf', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scan', schema=None) as batch_op:
        batch_op.drop_column('report_pdf')
        batch_op.drop_column('overall_score')
        batch_op.drop_column('posture_score')
        batch_op.drop_column('squat_score')
        batch_op.drop_column('stepping_score')
        batch_op.drop_column('balance_score')

    # ### end Alembic commands ###
